display_name: "🦷 Ассистент стоматолога"

retriever:
  # Количество самых релевантных фрагментов текста для поиска
  top_k: 3
  # Размер одного фрагмента текста (в символах)
  chunk_size: 1000
  # Пересечение между фрагментами (в символах) для сохранения контекста
  chunk_overlap: 200